spring:
  application:
    name: ContentManagementApi
  web:
    resources:
      static-locations:
        - classpath:/api/
  neo4j:
    uri: neo4j+s://6a2ca604.databases.neo4j.io
    authentication:
      username: neo4j
      password: CeCkmRS4il8LJyZpxj-6M2AgF10K8gTfQb3R2qqT4R4

app:
  storage:
    path: "D:\\Development\\ContentManagementApiStorage"
  knowledge-base:
    path: knowledge-base
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-4o
      temperature: '0.7'
      log-requests: true
      log-responses: true
      response-format: json_object
      timeout: 200000
logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: mappings
  health:
    neo4j:
      enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    url: /open_api_spec.yaml
